### ISSUE TITLE
Installation of requirements.txt with pip fails on sphinxcontrib-fulltoc

### ISSUE THREAD

**Issue by LeShadow** [ElasticHQ/elasticsearch-HQ#343]
When I try to install elasticHQ, when i'm on the step of using pip to install all requirements, I get the following error:

```
Collecting sphinxcontrib-fulltoc==1.2.0 (from -r requirements.txt (line 40))
  Using cached sphinxcontrib-fulltoc-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/www/html/python/lib/python3.5/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/var/www/html/python/lib/python3.5/site-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/var/www/html/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/var/www/html/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/var/www/html/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/var/www/html/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/var/www/html/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/var/www/html/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/var/www/html/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/var/www/html/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/var/www/html/python/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ahhs8p1h/sphinxcontrib-fulltoc/
```

**Comment by royrusso** [comment]
Can you try: 

`pip install --upgrade pip setuptools`

**Comment by royrusso** [comment]
I think I will separate the docs generation requirements from the app, to avoid this in the future.
