### ISSUE TITLE
Cannot start application 

### ISSUE THREAD

**Issue by hobakill** [ElasticHQ/elasticsearch-HQ#351]
```
root@myserver:~/elasticsearch-HQ# python application.py
Traceback (most recent call last):
  File "application.py", line 1, in <module>
    from elastichq import factory
  File "/root/elasticsearch-HQ/elastichq/factory.py", line 4, in <module>
    from elastichq.globals import init_log, init_database, init_marshmallow, init_scheduler
  File "/root/elasticsearch-HQ/elastichq/globals.py", line 10, in <module>
    from .config import settings
  File "/root/elasticsearch-HQ/elastichq/config/settings.py", line 3, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache
```

tried to `pip install lru_cache` bu that didn't help at all. 

noticed this when trying to `pip install functools` 

```
Collecting functools
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached functools-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/usr/lib/python2.7/dist-packages/setuptools/extension.py", line 3, in <module>
        import functools
      File "functools.py", line 72, in <module>
        globals()['c_%s' % x] = globals()[x] = getattr(_functools, x)
    AttributeError: 'module' object has no attribute 'compose'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wLyjYu/functools/
```

running python 2.7 FWIW

**Comment by royrusso** [comment]
This won't work. Minimum requirements are Python 3.4. We test on 3.6.
