### ISSUE TITLE
python application.py fails

### ISSUE THREAD

**Issue by Sjaak01** [ElasticHQ/elasticsearch-HQ#352]
When I run the command I get 
```

/elasticsearch-HQ-master$ python application.py
Traceback (most recent call last):
  File "application.py", line 1, in <module>
    from elastichq import factory
  File "/home/ubuntu/elasticsearch-HQ-master/elastichq/factory.py", line 4, in <module>
    from elastichq.globals import init_log, init_database, init_marshmallow, init_scheduler
  File "/home/ubuntu/elasticsearch-HQ-master/elastichq/globals.py", line 10, in <module>
    from .config import settings
  File "/home/ubuntu/elasticsearch-HQ-master/elastichq/config/settings.py", line 3, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache
```
How can I fix this? Running python3 application.py doesn't work either.

```
/elasticsearch-HQ-master$ python3 application.py
Traceback (most recent call last):
  File "application.py", line 1, in <module>
    from elastichq import factory
  File "/home/ubuntu/elasticsearch-HQ-master/elastichq/factory.py", line 2, in <module>
    from flask import Flask
ImportError: No module named 'flask'
```

**Comment by royrusso** [comment]
Did you follow the steps in the installation guide and install the requirements? You should probably use something like ``pip3 install -r requirements.txt``

**Comment by Sjaak01** [comment]
Thanks, running pip3 install -r requirements.txt and then python3 application.py works.

**Comment by royrusso** [comment]
Running just `pip`, depending on your system, may be using version 2.7. `pip3` will attempt to force it to use v3.x

**Comment by kikoreis** [comment]
To make installation as easy as possible, this should probably be noted in the docs as it's really unclear; many (most?) users trying this out will be on Ubuntu, which uses pip3. It is also necessary to install python3-pip (i.e. apt install python3-pip).
