### ISSUE TITLE
Cannot list indices on AWS Elasticsearch

### ISSUE THREAD

**Issue by curry684** [ElasticHQ/elasticsearch-HQ#371]
Running on Docker with latest (3.3.0), I'm getting all information, including clusters, nodes, diagnostics and everything, but no indices.

JS console notes:
```
GET http://localhost:5000/api/indices/785857882783:censored/_summary 500 (INTERNAL SERVER ERROR)
cluster-details.controller.js:24 ---- err:  {data: {…}, status: 500, headers: ƒ, config: {…}, statusText: "INTERNAL SERVER ERROR", …}
angular.js:14791 Possibly unhandled rejection: {"data":{"message":"Oops! Something bad happened.","status_code":500},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/indices/785857882783:censored/_summary","timeout":{},"headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"INTERNAL SERVER ERROR","xhrStatus":"complete"}
```
Regrettably, no further information. The Docker logs only contain startup information (they should likely forward error logs). Inside the container I cannot find any relevant logfiles.

**Comment by curry684** [comment]
ES is standard Amazon AWS Elasticsearch 5.1.1, Docker image for HQ is latest which is 3.3.0.

In the application log I get:
```
2018-04-16 20:43:42,316 	 ERROR 	 elastichq 	 exceptions._request_wrapper:37 	 Oops! Something bad happened.
Traceback (most recent call last):
  File "/src/elastichq/common/exceptions.py", line 29, in _request_wrapper
    return functor(*args, **kwargs)
  File "/src/elastichq/api/indices.py", line 28, in get
    response = IndicesService().get_indices_summary(cluster_name, index_names)
  File "/src/elastichq/service/IndicesService.py", line 115, in get_indices_summary
    'number_of_shards': int(jmespath.search("settings.index.number_of_shards", index_state)),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
Like I said, all other functions work fine, it's just fetching indices. It's also quite obviously a bug and not "help wanted"  😉

**Comment by curry684** [comment]
Same error btw on every page that lists indices anywhere, like for example the Alias detail page.

**Comment by royrusso** [comment]
The call to ES under IndicesService is the stats call: `http://localhost:5000/api/indices/<CLUSTER_NAME>/_summary`

Can you show me what that outputs. Running on 5.x seems to work, so this may be an issue with the AWS instances. I can add a hot patch, but am concerned also with what else is missing in that call.

**Comment by curry684** [comment]
There's no settings key in the index details on that call:
```
     "test-for-elastichq": {
        "state": "open",
        "mappings": {
          
        },
        "aliases": Array[0][
          
        ],
        "primary_terms": {
          "0": 1,
          "1": 1,
          "2": 1,
          "3": 1,
          "4": 1
        },
        "in_sync_allocations": {
          "0": Array[2][
            "Ry_itGl7SjK-8uRJ_zbJNA",
            "rph2QOhCSvGm4FQX58Cc5A"
          ],
          "1": Array[2][
            "r_73Waj4QFaBvbz7isb19w",
            "6G1TOTtOTqqSl5bQ1Quqiw"
          ],
          "2": Array[2][
            "sdh5-TPqRgSGcG1diSMn2g",
            "eREai22pT5eWlJTLekx4Ng"
          ],
          "3": Array[2][
            "kGgyQq5SS7SmvqFs8HhcxA",
            "PG9F9S0nREOV2uTNXPQkQg"
          ],
          "4": Array[2][
            "1E7AkGFPQry1PYNl8h4cDw",
            "wIR2sUCsT5WC3frIu4NnPA"
          ]
        }
      },
```

**Comment by curry684** [comment]
I can confirm docker image `elastichq/elasticsearch-hq:develop` is working fine, no errors anywhere in the entire app  👍

**Comment by royrusso** [comment]
That's fair. I patched both develop and master. Master is currently 3.3.0. I also renamed the docker image, as it was labeled "latest", when it should be "master".

**Comment by curry684** [comment]
Best practice for Docker is to alias `latest` to the "recommend for general audience" image, which would be 3.3.0 in this case, as it's the one that gets downloaded when no tag is specified.
