### ISSUE TITLE
SSL support in ElasticHQ

### ISSUE THREAD

**Issue by chitenderkumar** [ElasticHQ/elasticsearch-HQ#376]
with reference to #375  it would be great if we can get the SSL support in ElasticHQ to connect to Elasticsearch endpoint which are behind the proxy servers over the SSL/TLS protocols.

kindly let me know if any information require from my end.

**Comment by chngtrn** [comment]
I've found a way to enable SSL using a CA pem file and have tested it. How do I go about making a pull request to merge the feature?

**Comment by royrusso** [comment]
Thanks! Here's instructions:  https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request

**Comment by chngtrn** [comment]
Uhm. I don't have permission to push to this repo. Got the error below.

remote: Permission to ElasticHQ/elasticsearch-HQ.git denied to chngtrn.
fatal: unable to access 'https://github.com/ElasticHQ/elasticsearch-HQ/': The requested URL returned error: 403

**Comment by royrusso** [comment]
Ah yes. Looks like the instructions don't mention the important part... you have to fork the repo first.

**Comment by chngtrn** [comment]
Nevermind. Let me fork it and do a PR.

**Comment by chngtrn** [comment]
Create PR 390 below.

https://github.com/ElasticHQ/elasticsearch-HQ/pull/390

**Comment by royrusso** [comment]
I merged the PR in to develop for now. It'll go out with the next release (this week). Thanks!

**Comment by chngtrn** [comment]
Thanks.

**Comment by aderumeau** [comment]
Great, this should work with elassandra (elasticsearch+cassandra).
Thanks.

**Comment by alex-rad** [comment]
@chngtrn can you give us instruction on how to fix the SSL connection ? I tried to modify the 3 files and also to download the dev version but it didn't worked.

Thanks

**Comment by chngtrn** [comment]
@alex-rad Make sure your dev branch has the changes made in pull request below. Then run the app with --enable-ssl and --ca-certs flags like below. Your CA file must be the signer of your ES nodes otherwise you'll get untrust errors.

`python -m application --enable-ssl --ca-certs /path/to/your/ca.crt`

https://github.com/ElasticHQ/elasticsearch-HQ/pull/390/files

**Comment by royrusso** [comment]
These changes should now be part of the master branch. The release from yesterday, 3.4.0, should have the ssl additions merged in now also.

**Comment by alex-rad** [comment]
@chngtrn  @royrusso Thanks for the help. Please tell me, this implementation works also with Search Guard (like https://user:pass@ip:port on Elastic Search) ?

Regards

**Comment by chngtrn** [comment]
It definitely works with Searh Guard. We use SG. You should test it with admin user and narrow it down from there. If it's SSL error you'll see it in the console output.

I would test talking to your ES cluster using curl with your CA certificate to see if it's working. Something like the command below.

`curl -u admin:password --cacert /path/to/ca.crt https://localhost:9200/_cluster/settings?pretty`

**Comment by chngtrn** [comment]
Oh. I've ran into that recursion error too. It's the problem with python 3.6. You have to run it using 3.4 or 3.5. I used 3.4 and it's fine.

**Comment by alex-rad** [comment]
Thanks guys. I tried on a localhost node of ES, with python3.4, Indeed, the recursion error disappeared, but still not working on SSL. I tried with Search Guard deactivated and it works fine.

```
root@ip-172-31-32-48 elastic-hq]# python3.4 -m application --enable-ssl --ca-certs /etc/elasticsearch/root-ca.pem 
config settings.json not found, searched /etc/elastic-hq/settings.json,~/settings.json,/etc/elastic-hq/settings.json,/etc/elastic-hq/elastichq/settings.json,/etc/elastic-hq/elastichq/config/settings.json
loading config /etc/elastic-hq/elastichq/config/logger.json
2018-05-16 17:25:59,476 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._cursor_execute:1254 	 SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2018-05-16 17:25:59,477 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._cursor_execute:1255 	 ()
2018-05-16 17:25:59,477 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._cursor_execute:1254 	 SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2018-05-16 17:25:59,477 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._cursor_execute:1255 	 ()
2018-05-16 17:25:59,478 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1151 	 PRAGMA table_info("cluster")
2018-05-16 17:25:59,478 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1154 	 ()
2018-05-16 17:25:59,481 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._begin_impl:682 	 BEGIN (implicit)
2018-05-16 17:25:59,482 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1151 	 SELECT cluster.cluster_name AS cluster_cluster_name, cluster.cluster_ip AS cluster_cluster_ip, cluster.cluster_port AS cluster_cluster_port, cluster.cluster_scheme AS cluster_cluster_scheme, cluster.cluster_version AS cluster_cluster_version, cluster.cluster_username AS cluster_cluster_username, cluster.cluster_password AS cluster_cluster_password 
FROM cluster
2018-05-16 17:25:59,482 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1154 	 ()
2018-05-16 17:25:59,494 	 INFO 	 engineio 	 server.__init__:132 	 Server initialized for eventlet.
2018-05-16 17:28:16,154 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._begin_impl:682 	 BEGIN (implicit)
2018-05-16 17:28:16,155 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1151 	 SELECT cluster.cluster_name AS cluster_cluster_name, cluster.cluster_ip AS cluster_cluster_ip, cluster.cluster_port AS cluster_cluster_port, cluster.cluster_scheme AS cluster_cluster_scheme, cluster.cluster_version AS cluster_cluster_version, cluster.cluster_username AS cluster_cluster_username, cluster.cluster_password AS cluster_cluster_password 
FROM cluster
2018-05-16 17:28:16,155 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1154 	 ()
2018-05-16 17:28:16,161 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._rollback_impl:702 	 ROLLBACK
2018-05-16 17:28:16,299 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._begin_impl:682 	 BEGIN (implicit)
2018-05-16 17:28:16,300 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1151 	 SELECT cluster.cluster_name AS cluster_cluster_name, cluster.cluster_ip AS cluster_cluster_ip, cluster.cluster_port AS cluster_cluster_port, cluster.cluster_scheme AS cluster_cluster_scheme, cluster.cluster_version AS cluster_cluster_version, cluster.cluster_username AS cluster_cluster_username, cluster.cluster_password AS cluster_cluster_password 
FROM cluster
2018-05-16 17:28:16,300 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1154 	 ()
2018-05-16 17:28:16,305 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._rollback_impl:702 	 ROLLBACK
2018-05-16 17:28:16,428 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._begin_impl:682 	 BEGIN (implicit)
2018-05-16 17:28:16,429 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1151 	 SELECT cluster.cluster_name AS cluster_cluster_name, cluster.cluster_ip AS cluster_cluster_ip, cluster.cluster_port AS cluster_cluster_port, cluster.cluster_scheme AS cluster_cluster_scheme, cluster.cluster_version AS cluster_cluster_version, cluster.cluster_username AS cluster_cluster_username, cluster.cluster_password AS cluster_cluster_password 
FROM cluster
2018-05-16 17:28:16,429 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1154 	 ()
2018-05-16 17:28:16,435 	 DEBUG 	 elastichq 	 status.get:63 	 {"current_stable_version": "3.4.0", "tagline": "You know, for Elasticsearch", "installed_version": "3.4.0", "default_url": "http://localhost:9200", "clusters": [{"cluster_name": "es-cluster", "cluster_ip": "localhost", "cluster_port": "9200", "cluster_scheme": "http", "cluster_connected": false, "cluster_host": "http://localhost:9200", "cluster_version": "6.2.4", "cluster_health": null, "cluster_settings": null}], "name": "ElasticHQ"}
2018-05-16 17:28:16,436 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._rollback_impl:702 	 ROLLBACK
--- Logging error ---
Traceback (most recent call last):
  File "/etc/elastic-hq/elastichq/service/ConnectionService.py", line 62, in create_connection
    timeout=REQUEST_TIMEOUT, verify=ca_certs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib64/python3.4/ssl.py", line 656, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
SystemError: error return without exception set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.4/site-packages/eventlet/greenthread.py", line 218, in main
    result = function(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 781, in process_request
    proto.__init__(conn_state, self)
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 335, in __init__
    self.handle()
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 368, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 442, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 539, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.4/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/usr/lib/python3.4/site-packages/engineio/middleware.py", line 49, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/etc/elastic-hq/elastichq/common/exceptions.py", line 29, in _request_wrapper
    return functor(*args, **kwargs)
  File "/etc/elastic-hq/elastichq/api/clusters.py", line 121, in post
    enable_ssl=enable_ssl, ca_certs=ca_certs)
  File "/etc/elastic-hq/elastichq/service/ConnectionService.py", line 116, in create_connection
    LOG.error(message, ex)
Message: 'Unable to create connection to: https://localhost:9200'
Arguments: (SystemError('error return without exception set',),)
--- Logging error ---
Traceback (most recent call last):
  File "/etc/elastic-hq/elastichq/service/ConnectionService.py", line 62, in create_connection
    timeout=REQUEST_TIMEOUT, verify=ca_certs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib64/python3.4/ssl.py", line 656, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
SystemError: error return without exception set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python3.4/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.4/site-packages/eventlet/greenthread.py", line 218, in main
    result = function(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 781, in process_request
    proto.__init__(conn_state, self)
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 335, in __init__
    self.handle()
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 368, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 442, in handle_one_request
    self.handle_one_response()
  File "/usr/lib/python3.4/site-packages/eventlet/wsgi.py", line 539, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.4/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/usr/lib/python3.4/site-packages/engineio/middleware.py", line 49, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/etc/elastic-hq/elastichq/common/exceptions.py", line 29, in _request_wrapper
    return functor(*args, **kwargs)
  File "/etc/elastic-hq/elastichq/api/clusters.py", line 121, in post
    enable_ssl=enable_ssl, ca_certs=ca_certs)
  File "/etc/elastic-hq/elastichq/service/ConnectionService.py", line 116, in create_connection
    LOG.error(message, ex)
Message: 'Unable to create connection to: https://localhost:9200'
Arguments: (SystemError('error return without exception set',),)
2018-05-16 17:28:21,647 	 ERROR 	 elastichq 	 exceptions._request_wrapper:37 	 Oops! Something bad happened.
Traceback (most recent call last):
  File "/etc/elastic-hq/elastichq/common/exceptions.py", line 29, in _request_wrapper
    return functor(*args, **kwargs)
  File "/etc/elastic-hq/elastichq/api/clusters.py", line 121, in post
    enable_ssl=enable_ssl, ca_certs=ca_certs)
  File "/etc/elastic-hq/elastichq/service/ConnectionService.py", line 117, in create_connection
    raise ex
  File "/etc/elastic-hq/elastichq/service/ConnectionService.py", line 62, in create_connection
    timeout=REQUEST_TIMEOUT, verify=ca_certs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.4/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.4/site-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib64/python3.4/ssl.py", line 656, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
SystemError: error return without exception set

[root@ip-172-31-32-48 elastic-hq]curl -u admin:pass --cacert /etc/elasticsearch/root-ca.pem https://localhost:9200/_cluster/settings?pretty
{
  "persistent" : { },
  "transient" : { }
}
```

**Comment by chngtrn** [comment]
As you can see that the CN for the demo node cert is `node-0.example.com` which I'm pretty sure your ES node's hostname is not named that. My only other suggestion would be to create a CA and sign a cert for your ES nodes using the hostname of the ES nodes as then CN for each node and set `searchguard.ssl.transport.enforce_hostname_verification: true` and remove `searchguard.allow_unsafe_democertificates: true` line. Our instance with SG works fine; not using the demo certs that is.

**Comment by alex-rad** [comment]
Thanks @chngtrn. I will try with new certificates. I also tried the node-0.example.com (after I set it as a hostname, of course) and it throws the same error (but anyway, the cert is also signed for localhost)

**Comment by chngtrn** [comment]
That's the curl command parameter. The python application paramter is `--ca-certs` while curl us `--cacert`.


$ curl -h | grep cert
--cacert FILE   CA certificate to verify peer against (SSL)

**Comment by royrusso** [comment]
Ah. Sorry.. you're correct. I was building out the documentation and got confused. ;-)
