### ISSUE TITLE
Installing on Centos 7

### ISSUE THREAD

**Issue by chitraj8** [ElasticHQ/elasticsearch-HQ#384]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:MAC OS
- **ElasticHQ Version**:https://github.com/ElasticHQ/elasticsearch-HQ whichever shown latest
- **Elasticsearch Version**:5.6
- **Python version**: 2.7
- **Browser Vendor and Version (if applicable)**:

### Issue Description

I cloned the project to run locally on my Mac OS and found issues with installation.
I didnt modify anything in requirements.txt

### Source Code / Logs
pip install -r requirements.txt

e, coverage, nose, Flask-Testing, py, pytest, pytest-cov, pytest-ordering, funcsigs, tzlocal, futures, apscheduler, Flask-APScheduler, python-engineio, python-socketio, Flask-SocketIO, greenlet, eventlet
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 326, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 834, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1037, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/jmespath-0.9.3.dist-info'

Large logs and files should be attached. Try to provide a reproducible test case or steps that are the bare minimum necessary to generate the problem.

**Comment by royrusso** [comment]
On a Mac, the default python install  is 2.7, so you should set up a 3.4+ python virtual environment or use the docker distribution.
