### ISSUE TITLE
Run Fails on lru_cache

### ISSUE THREAD

**Issue by swizzley** [ElasticHQ/elasticsearch-HQ#398]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux release 7.5.1804 (Core) 
- **ElasticHQ Version**: master
- **Elasticsearch Version**: "2.4.6",
- **Python version**: Python 3.4.8
- **Browser Vendor and Version (if applicable)**: n/a

### Issue Description

Does not run. 

### Source Code / Logs

 File "application.py", line 5, in <module>
    from elastichq import create_app
  File "/home/vagrant/elasticsearch-HQ-master/elastichq/__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "/home/vagrant/elasticsearch-HQ-master/elastichq/api/endpoints.py", line 4, in <module>
    from . import clusters
  File "/home/vagrant/elasticsearch-HQ-master/elastichq/api/clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "/home/vagrant/elasticsearch-HQ-master/elastichq/model/__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "/home/vagrant/elasticsearch-HQ-master/elastichq/model/ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "/home/vagrant/elasticsearch-HQ-master/elastichq/globals.py", line 15, in <module>
    from .config import settings
  File "/home/vagrant/elasticsearch-HQ-master/elastichq/config/settings.py", line 2, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache

**Comment by swizzley** [comment]
pip install functools
Collecting functools
  Downloading https://files.pythonhosted.org/packages/22/3c/33589bf30422a92cf8c77054f2cf940ef2acc8a2857e5664045ed75a1c6a/functools-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.4/site-packages/setuptools/__init__.py", line 4, in <module>
        import functools
      File "/tmp/pip-install-nl03knxj/functools/functools.py", line 34
        raise TypeError, 'compose expects at least one argument'
                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-nl03knxj/functools/

**Comment by swizzley** [comment]
fix: https://github.com/ElasticHQ/elasticsearch-HQ/pull/399

**Comment by royrusso** [comment]
Merged. Thanks!
