### ISSUE TITLE
build test fails

### ISSUE THREAD

**Issue by KlavsKlavsen** [ElasticHQ/elasticsearch-HQ#401]
### General information
Linux Ubuntu 16.04
ElasticHQ Version 3.4.0 (clone of master from today actually)
Python version: 3.5

### Issue Description

When trying to package up elasticsearch-hq as a debian package - it fails during testing :(
saying:  missing 2 required positional arguments: 'cluster_name' and 'cluster_ip'

### Source Code / Logs
```
running test
running egg_info
writing requirements to elastichq.egg-info/requires.txt
writing dependency_links to elastichq.egg-info/dependency_links.txt
writing top-level names to elastichq.egg-info/top_level.txt
writing elastichq.egg-info/PKG-INFO
reading manifest file 'elastichq.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'elastichq.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    install_requires=requirements,
  File "/home/klk/elasticsearch-hq-3.4.0/debian/elasticsearch-hq/usr/share/python/elasticsearch-hq/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/klk/elasticsearch-hq-3.4.0/debian/elasticsearch-hq/usr/share/python/elasticsearch-hq/lib/python3.5/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/home/klk/elasticsearch-hq-3.4.0/debian/elasticsearch-hq/usr/share/python/elasticsearch-hq/lib/python3.5/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.5/unittest/main.py", line 117, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/klk/elasticsearch-hq-3.4.0/debian/elasticsearch-hq/usr/share/python/elasticsearch-hq/lib/python3.5/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.5/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/klk/elasticsearch-hq-3.4.0/debian/elasticsearch-hq/usr/share/python/elasticsearch-hq/lib/python3.5/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.5/unittest/loader.py", line 204, in loadTestsFromName
    test = obj()
TypeError: __init__() missing 2 required positional arguments: 'cluster_name' and 'cluster_ip'

```

**Comment by KlavsKlavsen** [comment]
I skipped the tests using:
```DEB_BUILD_OPTIONS=nocheck debuild -i -us -uc```

as they are not built to work when building debian packages (they don't startup whats needed before the test runs).

**Comment by royrusso** [comment]
Thanks @KlavsKlavsen , 

The codebase has diverged from the tests that were written a while ago, and so they've been failing. I'll fix them in the current release, to make things a bit easier.
