### ISSUE TITLE
comma is missing and server does not start

### ISSUE THREAD

**Issue by smmortazavi** [ElasticHQ/elasticsearch-HQ#415]
https://github.com/ElasticHQ/elasticsearch-HQ/blob/f427f9f7ffea0bbb9034774964cf6245749f393f/manage.py#L79

The above line is missing the , and therefore the following error is shown when starting the sever

> 2018-07-20 11:32:45,773 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1151 	 SELECT cluster.cluster_name AS cluster_cluster_name, cluster.cluster_ip AS cluster_cluster_ip, cluster.cluster_port AS cluster_cluster_port, cluster.cluster_scheme AS cluster_cluster_scheme, cluster.cluster_version AS cluster_cluster_version, cluster.cluster_username AS cluster_cluster_username, cluster.cluster_password AS cluster_cluster_password 
FROM cluster
2018-07-20 11:32:45,773 	 INFO 	 sqlalchemy.engine.base.Engine 	 base._execute_context:1154 	 ()
2018-07-20 11:32:45,780 	 INFO 	 engineio 	 server.__init__:133 	 Server initialized for eventlet.
Traceback (most recent call last):
  File "./manage.py", line 119, in <module>
    manager.run()
  File "/home/user/.virtualenvs/eshq/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/user/.virtualenvs/eshq/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "./manage.py", line 80, in __call__
    **self.server_options)
TypeError: <__main__.Server object at 0x7f38d53375f8>: unsupported operand type(s) for ** or pow(): 'bool' and 'dict'

**Comment by royrusso** [comment]
Thanks. I hope to push a patch release next week.
