### ISSUE TITLE
ModuleNotFoundError: No module named 'engineio.async_tornado'

### ISSUE THREAD

**Issue by ct-murali** [ElasticHQ/elasticsearch-HQ#416]
Traceback (most recent call last):
  File "application.py", line 5, in <module>
    from elastichq import create_app
  File "E:\elasticsearch-HQ\elastichq\__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "E:\elasticsearch-HQ\elastichq\api\endpoints.py", line 4, in <module>
    from . import clusters
  File "E:\elasticsearch-HQ\elastichq\api\clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "E:\elasticsearch-HQ\elastichq\model\__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "E:\elasticsearch-HQ\elastichq\model\ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "E:\elasticsearch-HQ\elastichq\globals.py", line 11, in <module>
    from flask_socketio import SocketIO
  File "C:\Users\Solutions\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_socketio\__init__.py", line 16, in <module>
    import socketio
  File "C:\Users\Solutions\AppData\Local\Programs\Python\Python37-32\lib\site-packages\socketio\__init__.py", line 11, in <module>
    from .tornado import get_tornado_handler
  File "C:\Users\Solutions\AppData\Local\Programs\Python\Python37-32\lib\site-packages\socketio\tornado.py", line 3, in <module>
    from engineio.async_tornado import get_tornado_handler as \
ModuleNotFoundError: No module named 'engineio.async_tornado'

**Comment by felipe-vvoosh** [comment]
I'm having the same issue...

**Comment by jrselzer** [comment]
Same issue on my Linux box (Ubuntu 16.04 LTS):

~/elasticsearch-HQ-master$ python3 application.py 
Traceback (most recent call last):
  File "application.py", line 5, in <module>
    from elastichq import create_app
  File "/home/jselzer/elasticsearch-HQ-master/elastichq/__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "/home/jselzer/elasticsearch-HQ-master/elastichq/api/endpoints.py", line 4, in <module>
    from . import clusters
  File "/home/jselzer/elasticsearch-HQ-master/elastichq/api/clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "/home/jselzer/elasticsearch-HQ-master/elastichq/model/__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "/home/jselzer/elasticsearch-HQ-master/elastichq/model/ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "/home/jselzer/elasticsearch-HQ-master/elastichq/globals.py", line 11, in <module>
    from flask_socketio import SocketIO
  File "/home/jselzer/.local/lib/python3.5/site-packages/flask_socketio/__init__.py", line 16, in <module>
    import socketio
  File "/home/jselzer/.local/lib/python3.5/site-packages/socketio/__init__.py", line 11, in <module>
    from .tornado import get_tornado_handler
  File "/home/jselzer/.local/lib/python3.5/site-packages/socketio/tornado.py", line 3, in <module>
    from engineio.async_tornado import get_tornado_handler as \
ImportError: No module named 'engineio.async_tornado'

**Comment by frutiger-it** [comment]
Same Issue on Debian 9.5

root@syslog6:/opt/elasticsearch-HQ-master#  python3 application.py
Traceback (most recent call last):
  File "application.py", line 5, in <module>
    from elastichq import create_app
  File "/opt/elasticsearch-HQ-master/elastichq/__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "/opt/elasticsearch-HQ-master/elastichq/api/endpoints.py", line 4, in <module>
    from . import clusters
  File "/opt/elasticsearch-HQ-master/elastichq/api/clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "/opt/elasticsearch-HQ-master/elastichq/model/__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "/opt/elasticsearch-HQ-master/elastichq/model/ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "/opt/elasticsearch-HQ-master/elastichq/globals.py", line 11, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/lib/python3.5/dist-packages/flask_socketio/__init__.py", line 16, in <module>
    import socketio
  File "/usr/local/lib/python3.5/dist-packages/socketio/__init__.py", line 11, in <module>
    from .tornado import get_tornado_handler
  File "/usr/local/lib/python3.5/dist-packages/socketio/tornado.py", line 3, in <module>
    from engineio.async_tornado import get_tornado_handler as \
ImportError: No module named 'engineio.async_tornado'

**Comment by Rylon** [comment]
I'm also experiencing this issue, Python 3.6.0.

**Comment by royrusso** [comment]
This issue popped up days ago without warning. I think a transitive dependency may have changed. It should be working now in the develop branch.
