### ISSUE TITLE
can't start elasticsearch-HQ

### ISSUE THREAD

**Issue by zqc0512** [ElasticHQ/elasticsearch-HQ#421]
version last 
centos 7.3 x86_64
python3.6.6

log
staring HQ:

```
[root@xxx elasticsearch-HQ-master]# python3 application.py 
config settings.json not found, searched /etc/elastic-hq/settings.json,~/settings.json,/root/elasticsearch-HQ/elasticsearch-HQ-master/settings.json,/root/elasticsearch-HQ/elasticsearch-HQ-master/elastichq/settings.json,/root/elasticsearch-HQ/elasticsearch-HQ-master/elastichq/config/settings.json
loading config /root/elasticsearch-HQ/elasticsearch-HQ-master/elastichq/config/logger.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 337, in dbapi
    from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```
also install sqlite3

```
[root@xxx ~]# sqlite3 
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> 
```

**Comment by royrusso** [comment]
Looks like you are missing requirements. Did you install them?

**Comment by zqc0512** [comment]
yes i use this to install with offline.
ony can connect to internet can start but the can't connect to internet machine can't start 

can connect internetwork machine:
i use 
`pip3 install -r requirements.txt
`
use  the flow  output the requirements packages.
```
pip3 freeze > requestments.txt   
pip3 download -d pgk/ -r requestments.txt
```
   scp the pgk directory to can't connect internetwork machine
```
cd pgk
pip install *
```
and starting elasticsearch-HQ  can't start.

the requestments.txt  is 

```
[root@test~]# more requ.txt 
alembic==1.0.0
aniso8601==3.0.2
APScheduler==3.5.0
certifi==2018.4.16
chardet==3.0.4
click==6.7
coverage==3.7.1
dogpile.cache==0.6.5
elastic-apm==1.0.0.dev2
elasticsearch==5.5.0
esrally==0.8.1
eventlet==0.23.0
Flask==0.12.2
Flask-APScheduler==1.7.1
flask-marshmallow==0.8.0
Flask-Migrate==2.2.1
Flask-RESTful==0.3.6
Flask-Script==2.0.6
Flask-SocketIO==3.0.1
Flask-SQLAlchemy==2.3.2
Flask-Testing==0.7.1
greenlet==0.4.14
idna==2.7
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.5.1
Mako==1.0.7
MarkupSafe==1.0
marshmallow==3.0.0b5
marshmallow-sqlalchemy==0.13.2
nose==1.3.4
psutil==5.4.0
py==1.5.4
py-cpuinfo==3.2.0
pytest==3.0.2
pytest-cov==2.3.1
pytest-ordering==0.5
python-dateutil==2.7.2
python-editor==1.0.3
python-engineio==2.2.0
python-socketio==2.0.0
pytz==2018.5
requests==2.19.1
six==1.11.0
SQLAlchemy==1.2.0
tabulate==0.8.1
thespian==3.8.0
tzlocal==1.5.1
urllib3==1.22
Werkzeug==0.14.1



```

**Comment by zqc0512** [comment]
can close slove it as

need reinstall sqlite and python3.6.6

```
$ wget https://www.sqlite.org/2017/sqlite-autoconf-3170000.tar.gz --no-check-certificate
$ tar zxvf sqlite-autoconf-3170000.tar.gz
$ cd sqlite-autoconf-3170000
$ ./configure --prefix=/usr/local/sqlite3 --disable-static --enable-fts5 --enable-json1 CFLAGS="-g -O2 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS4=1 -DSQLITE_ENABLE_RTREE=1"
$make && make install

$ cd Python-3.6.2
$ LD_RUN_PATH=/usr/local/sqlite3/lib ./configure LDFLAGS="-L/usr/local/sqlite3/lib" CPPFLAGS="-I /usr/local/sqlite3/include"
$ LD_RUN_PATH=/usr/local/sqlite3/lib make
$ LD_RUN_PATH=/usr/local/sqlite3/lib sudo make install
```
