### ISSUE TITLE
AttributeError: module 'engineio' has no attribute 'WSGIApp'

### ISSUE THREAD

**Issue by pleft** [ElasticHQ/elasticsearch-HQ#438]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **ElasticHQ Version**: v3.4.1
- **Elasticsearch Version**: 5.6.13
- **Python version**: 3.6.7 (64bit)
- **Browser Vendor and Version (if applicable)**:

### Issue Description

Cannot start application. Tried also with 32-bit python and with latest 3.7.1 python. It always fails with the following error:
`AttributeError: module 'engineio' has no attribute 'WSGIApp'`

### Source Code / Logs
```
pip install -r requirements.txt --no-cache-dir
Requirement already satisfied: jmespath==0.9.3 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 1)) (0.9.3)
Requirement already satisfied: Flask==0.12.2 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 4)) (0.12.2)
Requirement already satisfied: Flask-restful==0.3.6 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 5)) (0.3.6)
Requirement already satisfied: Flask-Script==2.0.6 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 6)) (2.0.6)
Requirement already satisfied: flask-marshmallow==0.8.0 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 9)) (0.8.0)
Requirement already satisfied: marshmallow-sqlalchemy==0.13.2 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 10)) (0.13.2)
Requirement already satisfied: marshmallow==3.0.0b5 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 11)) (3.0.0b5)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 14)) (1.22)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 15)) (2.20.1)
Requirement already satisfied: dogpile.cache==0.6.5 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 18)) (0.6.5)
Requirement already satisfied: SQLAlchemy==1.2.0 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 21)) (1.2.0)
Requirement already satisfied: Flask-SQLAlchemy==2.3.2 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 22)) (2.3.2)
Requirement already satisfied: Flask-Migrate in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 23)) (2.3.0)
Requirement already satisfied: coverage==3.7.1 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 26)) (3.7.1)
Requirement already satisfied: nose==1.3.4 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 27)) (1.3.4)
Requirement already satisfied: Flask-Testing in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 28)) (0.7.1)
Requirement already satisfied: pytest==3.0.2 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 29)) (3.0.2)
Requirement already satisfied: pytest-cov==2.3.1 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 30)) (2.3.1)
Requirement already satisfied: pytest-ordering==0.5 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 31)) (0.5)
Requirement already satisfied: apscheduler==3.5.0 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 35)) (3.5.0)
Requirement already satisfied: Flask-APScheduler==1.7.1 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 36)) (1.7.1)
Requirement already satisfied: python-engineio==2.2.0 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 39)) (2.2.0)
Requirement already satisfied: Flask-SocketIO==3.0.1 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 40)) (3.0.1)
Requirement already satisfied: eventlet==0.23.0 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 41)) (0.23.0)
Requirement already satisfied: six==1.11.0 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 47)) (1.11.0)
Requirement already satisfied: python-dateutil==2.7.2 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 48)) (2.7.2)
Requirement already satisfied: itsdangerous>=0.21 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from Flask==0.12.2->-r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: click>=2.0 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from Flask==0.12.2->-r requirements.txt (line 4)) (7.0)
Requirement already satisfied: Jinja2>=2.4 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from Flask==0.12.2->-r requirements.txt (line 4)) (2.10)
Requirement already satisfied: Werkzeug>=0.7 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from Flask==0.12.2->-r requirements.txt (line 4)) (0.14.1)
Requirement already satisfied: pytz in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from Flask-restful==0.3.6->-r requirements.txt (line 5)) (2018.7)
Requirement already satisfied: aniso8601>=0.82 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from Flask-restful==0.3.6->-r requirements.txt (line 5)) (4.0.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from requests<3.0.0,>=2.0.0->-r requirements.txt (line 15)) (2018.10.15)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from requests<3.0.0,>=2.0.0->-r requirements.txt (line 15)) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from requests<3.0.0,>=2.0.0->-r requirements.txt (line 15)) (3.0.4)
Requirement already satisfied: alembic>=0.7 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from Flask-Migrate->-r requirements.txt (line 23)) (1.0.3)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from pytest==3.0.2->-r requirements.txt (line 29)) (0.4.1)
Requirement already satisfied: py>=1.4.29 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from pytest==3.0.2->-r requirements.txt (line 29)) (1.7.0)
Requirement already satisfied: tzlocal>=1.2 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from apscheduler==3.5.0->-r requirements.txt (line 35)) (1.5.1)
Requirement already satisfied: setuptools>=0.7 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from apscheduler==3.5.0->-r requirements.txt (line 35)) (39.0.1)
Requirement already satisfied: python-socketio>=1.6.1 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from Flask-SocketIO==3.0.1->-r requirements.txt (line 40)) (2.1.0)
Requirement already satisfied: greenlet>=0.3 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from eventlet==0.23.0->-r requirements.txt (line 41)) (0.4.15)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from Jinja2>=2.4->Flask==0.12.2->-r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: Mako in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from alembic>=0.7->Flask-Migrate->-r requirements.txt (line 23)) (1.0.7)
Requirement already satisfied: python-editor>=0.3 in c:\users\p36510\appdata\local\programs\python\python36\lib\site-packages (from alembic>=0.7->Flask-Migrate->-r requirements.txt (line 23)) (1.0.3)
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
```
python application.py
Traceback (most recent call last):
  File "application.py", line 5, in <module>
    from elastichq import create_app
  File "C:\development\tools\elasticsearch-HQ\elastichq\__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "C:\development\tools\elasticsearch-HQ\elastichq\api\endpoints.py", line 4, in <module>
    from . import clusters
  File "C:\development\tools\elasticsearch-HQ\elastichq\api\clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "C:\development\tools\elasticsearch-HQ\elastichq\model\__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "C:\development\tools\elasticsearch-HQ\elastichq\model\ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "C:\development\tools\elasticsearch-HQ\elastichq\globals.py", line 8, in <module>
    from flask_socketio import SocketIO
  File "C:\Users\p36510\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_socketio\__init__.py", line 7, in <module>
    from socketio import socketio_manage
  File "C:\Users\p36510\AppData\Local\Programs\Python\Python36\lib\site-packages\socketio\__init__.py", line 10, in <module>
    from .middleware import WSGIApp, Middleware
  File "C:\Users\p36510\AppData\Local\Programs\Python\Python36\lib\site-packages\socketio\middleware.py", line 4, in <module>
    class WSGIApp(engineio.WSGIApp):
AttributeError: module 'engineio' has no attribute 'WSGIApp'
```

```
pip freeze
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
alembic==1.0.3
aniso8601==4.0.1
APScheduler==3.5.0
certifi==2018.10.15
chardet==3.0.4
Click==7.0
colorama==0.4.1
coverage==3.7.1
dogpile.cache==0.6.5
eventlet==0.23.0
Flask==0.12.2
Flask-APScheduler==1.7.1
flask-marshmallow==0.8.0
Flask-Migrate==2.3.0
Flask-RESTful==0.3.6
Flask-Script==2.0.6
Flask-SocketIO==3.0.1
Flask-SQLAlchemy==2.3.2
Flask-Testing==0.7.1
greenlet==0.4.15
idna==2.7
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
Mako==1.0.7
MarkupSafe==1.1.0
marshmallow==3.0.0b5
marshmallow-sqlalchemy==0.13.2
nose==1.3.4
py==1.7.0
pytest==3.0.2
pytest-cov==2.3.1
pytest-ordering==0.5
python-dateutil==2.7.2
python-editor==1.0.3
python-engineio==2.2.0
python-socketio==2.1.0
pytz==2018.7
requests==2.20.1
six==1.11.0
SQLAlchemy==1.2.0
tzlocal==1.5.1
urllib3==1.22
Werkzeug==0.14.1
```

**Comment by abidibo** [comment]
Same problem with ubuntu bionic 18.04, I've solved upgrading the python-engineio that was installed by requirements.txt.

requirements.txt version is 2.2.0, I've installed the 3.0.0. Now it works.

**Comment by pleft** [comment]
Updating `python-engineio` to `3.0.0` did the trick.

**Comment by heatonmatthew** [comment]
I found that updating `python-engineio` to `3.0.0` was necessary for me on Windows 10 also.

**Comment by royrusso** [comment]
Updating to 3.0.0 of engineio results in other issues in the development branch. Still looking at how to solve it.

**Comment by malinco** [comment]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian Jessie
ElasticHQ Version: v3.4.1
Python version: 3.4.2 (64bit)
Browser Vendor and Version (if applicable):

I run 'python3 application.py' and error occur:

Traceback (most recent call last):
  File "application.py", line 5, in <module>
    from elastichq import create_app
  File "/home/phavaadmin/work/elasticsearch-HQ-3.4.1/elastichq/__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "/home/phavaadmin/work/elasticsearch-HQ-3.4.1/elastichq/api/endpoints.py", line 4, in <module>
    from . import clusters
  File "/home/phavaadmin/work/elasticsearch-HQ-3.4.1/elastichq/api/clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "/home/phavaadmin/work/elasticsearch-HQ-3.4.1/elastichq/model/__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "/home/phavaadmin/work/elasticsearch-HQ-3.4.1/elastichq/model/ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "/home/phavaadmin/work/elasticsearch-HQ-3.4.1/elastichq/globals.py", line 8, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/lib/python3.4/dist-packages/flask_socketio/__init__.py", line 7, in <module>
    from socketio import socketio_manage
  File "/usr/local/lib/python3.4/dist-packages/socketio/__init__.py", line 10, in <module>
    from .middleware import WSGIApp, Middleware
  File "/usr/local/lib/python3.4/dist-packages/socketio/middleware.py", line 4, in <module>
    class WSGIApp(engineio.WSGIApp):
AttributeError: 'module' object has no attribute 'WSGIApp'

**Comment by abessifi** [comment]
I still experiment this issue since the last Python images update (about 20 days ago) on DockerHub (currently using the 3.6-alpine3.7 in the Dockerfile).  When I rebuild the image (elastichq 3.3.0) with the new python libs versions it works.

>added this to the 3.5.0 milestone 3 days ago

@royrusso what about previous releases ? Any bugfix propagation is planned for the previous  versions please ?

**Comment by abessifi** [comment]
As the python packages version are fixed in the upstream branch (develop in this case), the build of a new Docker image will work just fine.
My question is do people have to wait for the new 3.5.0 to be released or the fix will be applied on the previous releases (3.3.x, 3.4.x, etc) too ?

**Comment by royrusso** [comment]
Understood. I had no plans to backport the change to previous releases. I could attempt it, if you need so. The current state of the testing coverage isn't so good that I would feel comfortable, however.
