### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WSGIApp'

### ISSUE THREAD

**Issue by lailaiququ** [ElasticHQ/elasticsearch-HQ#444]
### General information

- ElasticHQ Version 3.4.1:
- Elasticsearch Version 5.4.0:
- Python version 2.7.9: 

### Issue Description
[root@i-qnpyaw7v elasticsearch-HQ-3.4.1]# /usr/bin/python application.py 
Traceback (most recent call last):
  File "application.py", line 5, in <module>
    from elastichq import create_app
  File "/usr/local/elk/elasticsearch-hq/elasticsearch-HQ-3.4.1/elastichq/__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "/usr/local/elk/elasticsearch-hq/elasticsearch-HQ-3.4.1/elastichq/api/endpoints.py", line 4, in <module>
    from . import clusters
  File "/usr/local/elk/elasticsearch-hq/elasticsearch-HQ-3.4.1/elastichq/api/clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "/usr/local/elk/elasticsearch-hq/elasticsearch-HQ-3.4.1/elastichq/model/__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "/usr/local/elk/elasticsearch-hq/elasticsearch-HQ-3.4.1/elastichq/model/ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "/usr/local/elk/elasticsearch-hq/elasticsearch-HQ-3.4.1/elastichq/globals.py", line 8, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/python27/lib/python2.7/site-packages/flask_socketio/__init__.py", line 7, in <module>
    from socketio import socketio_manage
  File "/usr/local/python27/lib/python2.7/site-packages/socketio/__init__.py", line 10, in <module>
    from .middleware import WSGIApp, Middleware
  File "/usr/local/python27/lib/python2.7/site-packages/socketio/middleware.py", line 4, in <module>
    class WSGIApp(engineio.WSGIApp):
AttributeError: 'module' object has no attribute 'WSGIApp'

**Comment by lailaiququ** [comment]
1，安装python3 
2，执行 python3 application.py 
3，出现新的问题，https://github.com/ElasticHQ/elasticsearch-HQ/issues/438
4，更新./pip3 install --upgrade python-engineio
5，success
