### ISSUE TITLE
Rejecting mapping update

### ISSUE THREAD

**Issue by sentient** [ElasticHQ/elasticsearch-HQ#453]
### General information
Rejecting mapping update to [.elastichq] as the final mapping would have more than 1 type: [data, doc]'

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
   Docker image 
- **ElasticHQ Version**:
    3.5.0
- **Elasticsearch Version**:
  6.3.2
- **Python version**: 
  3.6
- **Browser Vendor and Version (if applicable)**:
  chrome
### Issue Description

When clicking on Metrics all the graphs are empty. 

### Source Code / Logs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/engineio/server.py", line 423, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.6/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 251, in _handler
    *args)
  File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 634, in _handle_event
    ret = handler(*args)
  File "/src/elastichq/api/socket.py", line 61, in joined
    task_procesor(room_name, cluster_name=cluster_name, metric=metric)
  File "/src/elastichq/api/socket.py", line 44, in task_procesor
    task = Task(room_name=room_name, cluster_name=cluster_name, metric=metric)
  File "/src/elastichq/model/Task.py", line 33, in __init__
    self.loop_delay = HQService().get_settings(self.cluster_name).get('websocket_interval', 5)
  File "/usr/local/lib/python3.6/site-packages/dogpile/cache/region.py", line 1250, in decorate
    should_cache_fn)
  File "/usr/local/lib/python3.6/site-packages/dogpile/cache/region.py", line 844, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python3.6/site-packages/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/usr/local/lib/python3.6/site-packages/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python3.6/site-packages/dogpile/lock.py", line 145, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python3.6/site-packages/dogpile/cache/region.py", line 811, in gen_value
    created_value = creator()
  File "/usr/local/lib/python3.6/site-packages/dogpile/cache/region.py", line 1246, in creator
    return fn(*arg, **kw)
  File "/src/elastichq/service/HQService.py", line 58, in get_settings
    self.save_settings(cluster_name)
  File "/src/elastichq/service/HQService.py", line 70, in save_settings
    body=body, refresh=True)
  File "/src/elastichq/vendor/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/src/elastichq/vendor/elasticsearch/client/__init__.py", line 302, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/src/elastichq/vendor/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/src/elastichq/vendor/elasticsearch/connection/http_urllib3.py", line 163, in perform_request
    self._raise_error(response.status, raw_data)
  File "/src/elastichq/vendor/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elastichq.vendor.elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [.elastichq] as the final mapping would have more than 1 type: [data, doc]')
2019-01-03 19:43:29,199          INFO    engineio        socket._websocket_handler:203   e6b4cf57e5fb4df7b327f78311046505: Upgrade to websocket successful

**Comment by sentient** [comment]
I found the issue. 

I had a default template mapping defined on order:0 

once I removed that mapping it all worked fine.

```
 "mappings": {
        "doc": {
            "date_detection": false
        }
    },
```

**Comment by sunilchadha1973** [comment]
I am getting this error:
`elastichq.vendor.elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [.elastichq] as the final mapping would have more than 1 type: [_doc, data]')`

What steps you did to resolve this error?
