### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by wangtx** [ElasticHQ/elasticsearch-HQ#459]
### General information

- **Linux 2.6.32-504.el6.x86_64**:
- **ElasticHQ Version 3.5.0**:
- **Elasticsearch Version6.2.3**:
- **Python version3.6**: 
- **Browser Vendor and Version chrom**:

### Issue Description
metrics  can not display data
### Source Code / Logs

2019-02-27 16:39:22,040 	 ERROR 	 engineio 	 server._trigger_event:425 	 message handler error
Traceback (most recent call last):
  File "/opt/soft/python3.6/lib/python3.6/site-packages/engineio/server.py", line 423, in _trigger_event
    return self.handlers[event](*args)
  File "/opt/soft/python3.6/lib/python3.6/site-packages/socketio/server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/opt/soft/python3.6/lib/python3.6/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/opt/soft/python3.6/lib/python3.6/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/opt/soft/python3.6/lib/python3.6/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/opt/soft/python3.6/lib/python3.6/site-packages/flask_socketio/__init__.py", line 251, in _handler
    *args)
  File "/opt/soft/python3.6/lib/python3.6/site-packages/flask_socketio/__init__.py", line 634, in _handle_event
    ret = handler(*args)
  File "/opt/soft/elasticsearch-HQ-master/elastichq/api/socket.py", line 60, in joined
    print(rooms())
OSError: [Errno 5] Input/output error

**Comment by royrusso** [comment]
Are you running HQ behind nginx or apache?

**Comment by alieksanov** [comment]
Have the same issue:
`2019-05-07 14:37:37,613 	 ERROR 	 engineio 	 server._trigger_event:425 	 message handler error
Traceback (most recent call last):
  File "/opt/elastichq/lib/python3.5/site-packages/engineio/server.py", line 423, in _trigger_event
    return self.handlers[event](*args)
  File "/opt/elastichq/lib/python3.5/site-packages/socketio/server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/opt/elastichq/lib/python3.5/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/opt/elastichq/lib/python3.5/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/opt/elastichq/lib/python3.5/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/opt/elastichq/lib/python3.5/site-packages/flask_socketio/__init__.py", line 251, in _handler
    *args)
  File "/opt/elastichq/lib/python3.5/site-packages/flask_socketio/__init__.py", line 634, in _handle_event
    ret = handler(*args)
  File "/opt/elastichq/elastichq/api/socket.py", line 60, in joined
    print(rooms())
OSError: [Errno 5] Input/output error`

ElasticHQ running not behind proxy.
