### ISSUE TITLE
Cannot run after installation

### ISSUE THREAD

**Issue by GinoPane** [ElasticHQ/elasticsearch-HQ#474]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **ElasticHQ Version**: the latest
- **Elasticsearch Version**: -
- **Python version**: 3.6.7
- **Browser Vendor and Version (if applicable)**: - 

### Issue Description

The source code was downloaded, requirements were installed with no errors. But the server fails to start:

```
python3 application.py 
Traceback (most recent call last):
  File "application.py", line 6, in <module>
    from elastichq import create_app
  File "/home/siarheikaravai/Tools/elasticsearch-HQ/elastichq/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
```

```
python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    from elastichq import create_app
  File "/home/siarheikaravai/Tools/elasticsearch-HQ/elastichq/__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "/home/siarheikaravai/Tools/elasticsearch-HQ/elastichq/api/endpoints.py", line 4, in <module>
    from . import clusters
  File "/home/siarheikaravai/Tools/elasticsearch-HQ/elastichq/api/clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "/home/siarheikaravai/Tools/elasticsearch-HQ/elastichq/model/__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "/home/siarheikaravai/Tools/elasticsearch-HQ/elastichq/model/ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "/home/siarheikaravai/Tools/elasticsearch-HQ/elastichq/globals.py", line 12, in <module>
    from .config import settings
  File "/home/siarheikaravai/Tools/elasticsearch-HQ/elastichq/config/settings.py", line 2, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache
```

**Comment by taosha1** [comment]
me too...

**Comment by eatzombies** [comment]
had the same issue - found the solution at https://github.com/ElasticHQ/elasticsearch-HQ/issues/440

**Comment by royrusso** [comment]
> had the same issue - found the solution at #440

That's the solution... although I would recommend folks use the docker image unless they are planning to help with development. It's simply easier than dealing with all the python versioning issues.
