### ISSUE TITLE
Can't start the server: python application.py

### ISSUE THREAD

**Issue by BhagiLimbu** [ElasticHQ/elasticsearch-HQ#501]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **ElasticHQ Version**: Lastest Version clone source code from Github
- **Elasticsearch Version**:5.6.3
- **Python version (ignore is using docker image)**: 3.8.0
- **Browser Vendor and Version (if applicable)**:

### Issue Description
I install from source and follow instructions mention in the documentation - http://docs.elastichq.org/installation.html#install-from-source. When I run the command: "python application.py", It throws an exception - AttributeError: module 'time' has no attribute 'clock'.

### Source Code / Logs
C:\pythonworkspace\elasticsearch-HQ>python --version
Python 3.8.0

C:\pythonworkspace\elasticsearch-HQ>python application.py
Traceback (most recent call last):
  File "application.py", line 6, in <module>
    from elastichq import create_app
  File "C:\pythonworkspace\elasticsearch-HQ\elastichq\__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "C:\pythonworkspace\elasticsearch-HQ\elastichq\api\endpoints.py", line 4, in <module>
    from . import clusters
  File "C:\pythonworkspace\elasticsearch-HQ\elastichq\api\clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "C:\pythonworkspace\elasticsearch-HQ\elastichq\model\__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "C:\pythonworkspace\elasticsearch-HQ\elastichq\model\ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "C:\pythonworkspace\elasticsearch-HQ\elastichq\globals.py", line 6, in <module>
    from flask_marshmallow import Marshmallow
  File "C:\Python\Python38\lib\site-packages\flask_marshmallow\__init__.py", line 24, in <module>
    import flask_sqlalchemy  # flake8: noqa
  File "C:\Python\Python38\lib\site-packages\flask_sqlalchemy\__init__.py", line 22, in <module>
    import sqlalchemy
  File "C:\Python\Python38\lib\site-packages\sqlalchemy\__init__.py", line 9, in <module>
    from .sql import (
  File "C:\Python\Python38\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import (
  File "C:\Python\Python38\lib\site-packages\sqlalchemy\sql\expression.py", line 34, in <module>
    from .visitors import Visitable
  File "C:\Python\Python38\lib\site-packages\sqlalchemy\sql\visitors.py", line 28, in <module>
    from .. import util
  File "C:\Python\Python38\lib\site-packages\sqlalchemy\util\__init__.py", line 8, in <module>
    from .compat import callable, cmp, reduce,  \
  File "C:\Python\Python38\lib\site-packages\sqlalchemy\util\compat.py", line 172, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

### Be Patient

I have a day job. ;-)

**Comment by royrusso** [comment]
This looks like a SQLAlchemy / Py 3.8 issue. Either try a different version of python, or use the docker distro please.

**Comment by BhagiLimbu** [comment]
Which python version do you suggest?

**Comment by BhagiLimbu** [comment]
I tried docker, but keep failing connect with a local ElasticSearch. Do I need to change any config file to connect local ElasticSearch that is not running on Docker container?

**Comment by royrusso** [comment]
3.7 should work. 3.5 and 3.6 should as well. What failed with the docker distro?

**Comment by BhagiLimbu** [comment]
Thanks, let me change 3.6 and revert back to you if any issue. The docker failed to connect http://localhost:9200/  which is running at local machine not in local docker container.

`
C:\pythonworkspace\elasticsearch-HQ>docker run -p 5000:5000 elastichq/elasticsearch-hq
2019-10-24 03:54:26,220 CRIT Supervisor running as root (no user in config file)
2019-10-24 03:54:26,225 INFO supervisord started with pid 1
2019-10-24 03:54:27,228 INFO spawned: 'gunicorn' with pid 8
2019-10-24 03:54:28,231 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
loading config /src/elastichq/config/logger.json
2019-10-24 03:54:28,741          INFO    engineio        server.__init__:140     Server initialized for eventlet.
config settings.json not found, searched /etc/elastic-hq/settings.json,~/settings.json,/src/settings.json,/src/elastichq/settings.json,/src/elastichq/config/settings.json
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 267, in connect
    socket_checkerr(fd)
  File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 51, in socket_checkerr
    raise socket.error(err, errno.errorcode[err])
ConnectionRefusedError: [Errno 111] ECONNREFUSED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff74d59c390>: Failed to establish a new connection: [Errno 111] ECONNREFUSED

`

**Comment by Rahul-Chittora** [comment]
facing the same issue when docker is used

**Comment by k0t0fey** [comment]
Same issue with docker and python

**Comment by davidst2017** [comment]
Having the same issue. Any updates?

**Comment by igor-moskvitin** [comment]
Same issue occurred
