### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'data'

### ISSUE THREAD

**Issue by jlsanz-sdi** [ElasticHQ/elasticsearch-HQ#513]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Red Hat Enterprise Linux Server release 7.4 (Maipo)
- **ElasticHQ Version**:
I think the latest, 3.5.12
- **Elasticsearch Version**:
5.5
- **Python version (ignore is using docker image)**: 
3.6
- **Browser Vendor and Version (if applicable)**:

### Issue Description

I can start application.py and can recognize the cluster

But finally I got the following error

Traceback (most recent call last):
  File "/DATA/HQ/elasticsearch-HQ-master/elastichq/common/exceptions.py", line 29, in _request_wrapper
    return functor(*args, **kwargs)
  File "/DATA/HQ/elasticsearch-HQ-master/elastichq/api/clusters.py", line 133, in post
    return APIResponse(result.data, HTTP_Status.CREATED, None)
AttributeError: 'collections.OrderedDict' object has no attribute 'data'
[application.log](https://github.com/ElasticHQ/elasticsearch-HQ/files/4112047/application.log)

### Source Code / Logs

Include any logs or source code that would be helpful to diagnose the problem. If including stacktrace, please include the full stacktrace. 

Large logs and files should be attached. Try to provide a reproducible test case or steps that are the bare minimum necessary to generate the problem.

### Be Patient

I have a day job. ;-)

**Comment by jlsanz-sdi** [comment]
pip3.6 install -U 'marshmallow==2.16.1' did the trick
