### ISSUE TITLE
exceptions._request_wrapper:37  Oops!  Something bad happend.

### ISSUE THREAD

**Issue by Chaffy-0** [ElasticHQ/elasticsearch-HQ#543]
### General information
Debian 11
ESHQ 3.5.12
ES 6.8
Python 3.9.2

### Issue Description

The web gui launches just fine here: https://IPOFMYSERVER:5000 but when I try to connect to Elasticsearch I'm getting the below error in the application.log file.  I tried to connect to a node I have verified that ES is running.  The attached text file is a copy of the application.log file with debug set to True.

```
2021-09-30 14:11:23,699 	 ERROR 	 elastichq 	 exceptions._request_wrapper:37 	 Oops! Something bad happened.
Traceback (most recent call last):
  File "/root/elastichq/elasticsearch-HQ/elastichq/common/exceptions.py", line 29, in _request_wrapper
    return functor(*args, **kwargs)
  File "/root/elastichq/elasticsearch-HQ/elastichq/api/clusters.py", line 104, in post
    params.update(json_data)
TypeError: cannot convert dictionary update sequence element #0 to a sequence
```

### Be Patient
No problem!

I have a day job. ;-
[application.txt](https://github.com/ElasticHQ/elasticsearch-HQ/files/7262156/application.txt)
)

**Comment by cristhian-net** [comment]
Same problem here...

**Comment by T100D** [comment]
Same problem here,
  * Rocky linux 8.3
  * python 3.6.8
  * eshq latest version from master.zip

# python3 application.py
config settings.json not found, searched /etc/elastic-hq/settings.json,~/settings.json,/root/ElasticHQ/elasticsearch-HQ-master/settings.json,/root/ElasticHQ/elasticsearch-HQ-master/elastichq/settings.json,/root/ElasticHQ/elasticsearch-HQ-master/elastichq/config/settings.json
loading config /root/ElasticHQ/elasticsearch-HQ-master/elastichq/config/logger.json
2021-11-11 16:35:59,762   INFO   engineio        server.__init__:140     Server initialized for eventlet.
2021-11-11 16:36:14,819   ERROR   elastichq      exceptions._request_wrapper:37          Oops! Something bad happened.
Traceback (most recent call last):
  File "/root/ElasticHQ/elasticsearch-HQ-master/elastichq/common/exceptions.py", line 29, in _request_wrapper
    return functor(*args, **kwargs)
  File "/root/ElasticHQ/elasticsearch-HQ-master/elastichq/api/clusters.py", line 104, in post
    params.update(json_data)
TypeError: cannot convert dictionary update sequence element #0 to a sequence
[2021-11-11 16:36:14,821] ERROR in app: Exception on /api/clusters/_connect [POST]
Traceback (most recent call last):
  File "/root/ElasticHQ/elasticsearch-HQ-master/elastichq/common/exceptions.py", line 29, in _request_wrapper
    return functor(*args, **kwargs)
  File "/root/ElasticHQ/elasticsearch-HQ-master/elastichq/api/clusters.py", line 104, in post
    params.update(json_data)
TypeError: cannot convert dictionary update sequence element #0 to a sequence

**Comment by T100D** [comment]
Check this https://github.com/ElasticHQ/elasticsearch-HQ/issues/544 it solved our problem not able to connect to the clusters
