### ISSUE TITLE
ElasticHQ is now inoperable with ES 8.x

### ISSUE THREAD

**Issue by k0stett** [ElasticHQ/elasticsearch-HQ#549]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker
- **ElasticHQ Version**: latest
- **Elasticsearch Version**: 8.8.0
- **Python version (ignore is using docker image)**: 
- **Browser Vendor and Version (if applicable)**:

### Issue Description

Requesting `/.elastichq/data/` isn't working with elasticsearch 8.x, have to use `/.elastichq/_doc/` instead.

### Source Code / Logs

```
2023-06-05 08:25:06,879          WARNING         elasticsearch   base.log_request_fail:97        GET http://elastic1-1:9200/.elastichq/data/hqsettings/_source [status:400 request:0.004s]
2023-06-05 08:25:06,879          DEBUG   elasticsearch   base.log_request_fail:105       > None
2023-06-05 08:25:06,880          DEBUG   elasticsearch   base.log_request_fail:110       < {"error":"no handler found for uri [/.elastichq/data/hqsettings/_source] and method [GET]"}
2023-06-05 08:25:06,880          DEBUG   dogpile.lock    lock._enter_create:150          Released creation lock
2023-06-05 08:25:06,880          ERROR   elastichq       exceptions._request_wrapper:37          Oops! Something bad happened.
Traceback (most recent call last):
  File "/src/elastichq/common/exceptions.py", line 29, in _request_wrapper
    return functor(*args, **kwargs)
  File "/src/elastichq/api/indices.py", line 28, in get
    response = IndicesService().get_indices_summary(cluster_name, index_names)
  File "/src/elastichq/service/IndicesService.py", line 99, in get_indices_summary
    show_dot_indices = HQService().get_settings(cluster_name).get('show_dot_indices')
  File "/usr/local/lib/python3.6/site-packages/dogpile/cache/region.py", line 1250, in decorate
    should_cache_fn)
  File "/usr/local/lib/python3.6/site-packages/dogpile/cache/region.py", line 844, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python3.6/site-packages/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/usr/local/lib/python3.6/site-packages/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python3.6/site-packages/dogpile/lock.py", line 145, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python3.6/site-packages/dogpile/cache/region.py", line 811, in gen_value
    created_value = creator()
  File "/usr/local/lib/python3.6/site-packages/dogpile/cache/region.py", line 1246, in creator
    return fn(*arg, **kw)
  File "/src/elastichq/service/HQService.py", line 53, in get_settings
    'doc_type'])
  File "/src/elastichq/vendor/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/src/elastichq/vendor/elasticsearch/client/__init__.py", line 449, in get_source
    doc_type, id, '_source'), params=params)
  File "/src/elastichq/vendor/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/src/elastichq/vendor/elasticsearch/connection/http_urllib3.py", line 163, in perform_request
    self._raise_error(response.status, raw_data)
  File "/src/elastichq/vendor/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elastichq.vendor.elasticsearch.exceptions.RequestError: <unprintable RequestError object>

```

**Comment by Navirash** [comment]
@k0stett Do you find a solution about this error ?

**Comment by k0stett** [comment]
> @k0stett Do you find a solution about this error ?

Nope, just switched to use Kibana's new possibilities for administrating.

**Comment by j0nny55555** [comment]
Also facing this issue... though, on a new Docker roll, it works... it is only later that the error pops up and prevents re-connection

One would assume you could likely have a version 7.x and 8.x interaction modes, something for another day?
